general {
    lock_cmd = pidof hyprlock || hyprlock       # command to run when locking
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # wake up screen on resume
}

# 1. AUTO LOCK: 5 Minutes (300s) - Happens regardless of power state
listener {
    timeout = 600                                
    on-timeout = loginctl lock-session           
}

# 2. AUTO SLEEP: 30 Minutes (1800s) - ONLY if discharging (battery)
listener {
    timeout = 1800
    # 'systemd-ac-power' returns exit code 1 if on battery. 
    # The || operator runs the next command only if the first failed (i.e., we are NOT on AC).
    on-timeout = systemd-ac-power || systemctl suspend
}
